#!/bin/sh

for battery in /sys/class/power_supply/BAT?
do
    capacity=$(cat "$battery"/capacity 2>/dev/null) || break
    status=$(sed "s/[Dd]ischarging/D/;s/[Nn]ot charging/X/;s/[Cc]harging/C/;s/[Uu]nknown/U/;s/[Ff]ull/F/" "$battery"/status)

    # if 25% or less add n ! as a warning
    [ "$capacity" -le 25 ] && [ "$status" = "D" && warn="!"
    printf "%s%s%s%% \x08|\\n" "$status" "$warn" "$capacity"
done | sed 's/ *$//'
