#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
    2) setsid "$TERMINAL" -e htop & ;;
    3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# get the cpu %
cpu_pct () {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    echo "$cpu%"
}


cpu_temp () {
    res=$( sensors | awk '/Package id 0:/ {print $4}' )
    echo "$res"
}



#sensors | awk '/Core 0/ {print "🌡" $3 "|"}'
cpu=$(cpu_pct)
temp=$(cpu_temp)
echo "CPU $cpu, $temp |"
