#!/bin/sh

# get the cpu %
cpu_pct () {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    echo "$cpu%"
}


cpu_temp () {
    res=$( sensors | awk '/Package id 0:/ {print $4}' | sed -e 's/+//' )
    echo "$res"
}

cpu=$(cpu_pct)
temp=$(cpu_temp)
printf "\x08C %s, %s \x03|\\n" "$cpu" "$temp"
