#!/bin/sh

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
    down) wifisignal="0" ;;
    up) wifisignal="$(awk '/^\s*w/ { print "W("int($3 * 100 / 70) ")%" }' /proc/net/wireless)" ;;
esac

ethernet=$(sed "s/down//;s/up/E/" /sys/class/net/e*/operstate 2>/dev/null)

if [ -n "$ethernet" ] && [ -n "$wifisignal" ]
then
    printf "\x04 E+%s\\n" $wifisignal
elif [ -n "$ethernet" ]
then
    printf "\x04E\\n"
else
    printf "\x04 OFFLINE \\n"
fi

