#!/bin/sh

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
    down) wifisignal="" ;;
    up) wifisignal="$(awk '/^\s*w/ { print ""int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
esac

ethernet=$(sed "s/down//;s/up/E/" /sys/class/net/e*/operstate 2>/dev/null)

if [ -n "$ethernet" ] && [ -n "$wifisignal" ]
then
    printf "\x04+%s\\n" $wifisignal
elif [ -n "$ethernet" ]
then
    printf "\x04\\n"
elif [ -n "$wifisignal" ]
then
    printf "\x04%s\\n" $wifisignal
else
    printf "\x04OFFLINE \\n"
fi

