#!/bin/sh

# Displays number of upgradeable packages.

pkgs=$(checkupdates)
# only take an exit code of 0; 2 is no updates, 1 is an error
if [ $? -eq 0 ]
then
    # echo pkgs in quotes - otherwise the newlines are stripped 
    npkgs=$(echo "$pkgs" | wc -l)
    printf "\x05UPDATES: $npkgs \x03|\\n"
fi
