#!/bin/sh

# Prints the current volume or muted. Uses PulseAudio

volstat="$(pactl list sinks | grep -A 20 'State: RUNNING')"

echo "$volstat" | grep -q "Mute: yes" && printf "Muted\\n" && exit
# echo "$volstat" | grep "\[off\]" >/dev/null && printf "🔇\\n" && exit # ALSA

vol="$(echo "$volstat" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
vol="$(echo "$volstat" | grep "Volume" | grep -v "Base" | sed -e "s:.* \([0-9]\+\)%.*:\1:")"
# vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q") # ALSA

printf "\x06%3.0f%% \x03|\\n" "$vol"
