#!/bin/sh

# Prints the current volume or muted. Uses PulseAudio

volstat="$(pactl list sinks)"

echo "$volstat" | grep -q "Mute: yes" && printf "Muted\\n" && exit
# echo "$volstat" | grep "\[off\]" >/dev/null && printf "🔇\\n" && exit # ALSA

vol="$(echo "$volstat" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
# vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q") # ALSA

printf "\x06Vol:%3.0f%% \x08|\\n" "$vol"
